{% set name = "eo-learn-core" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d6888c6cbced2114f3b43729a5bdaba47ea7a88fe11dd7116d4049feb2778f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - attrs >=19.2.0
    - boto3
    - fs
    - fs-s3fs
    - geopandas >=0.8.1
    - numpy >=1.20.0
    - python-dateutil
    - sentinelhub >=3.4.4
    - tqdm >=4.27

test:
  imports:
    - eolearn
    - eolearn.core

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Core Machine Learning Framework at Sinergise
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.core.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
